project:
  type: website
  output-dir: docs
  
website:
  title: "Hochfrequente Strahlung im Massivholzbau"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - text: Messungen
        menu: 
        - href: messaufbau.qmd
          text: Messaufbau
        - href: messablauf.qmd
          text: Messablauf
        - href: ergebnisse.qmd
          text: Ergebnisse
      - href: interpretation.qmd
        text: Interpretation der Ergebnisse
    tools:
      - icon: instagram
        href: https://www.instagram.com/thoma_holz100/


format:
  html:
    theme: flatly
    toc: true
    css: quarto.css

editor: source

